services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: gcr.io/inreach-forecast-444900/inreach-grib-api
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=api.py
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}  # Ensures that the reloader and debugger are enabled
      - API_URL=${API_URL}
      - ECMWF_API_URL
      - ECMWF_API_KEY
      - ECMWF_API_EMAIL
      - GMAIL_APP_MAIL
      - GMAIL_APP_PASS
    volumes:
      - ./api:/app
    command: flask run --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: gcr.io/inreach-forecast-444900/inreach-grib-app
    ports:
      - "3000:80"
    environment:
      - API_URL=${API_URL}
    depends_on:
      - api
