services:
  api:
    platform: linux/x86_64  # Specify the platform here
    build:
      context: ./api
      dockerfile: Dockerfile
    image: gcr.io/inreach-forecast-444900/inreach-grib-api
    ports:
      - "8080:8080"  # Ensure this is 8080 for Google cloud
    environment:
      - FLASK_APP=api.py
      - FLASK_ENV=production
    volumes:
      - ./api:/app
    command: gunicorn --bind 0.0.0.0:8080 api:app  # Use Gunicorn

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: gcr.io/inreach-forecast-444900/inreach-grib-app
    ports:
      - "3000:80"
    environment:
      - API_URL=${API_URL}
    depends_on:
      - api
