version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=api.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1  # Ensures that the reloader and debugger are enabled
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=8000
